### ISSUE TITLE
[HW8] Работа с Git

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos21-onl/vadim-gleb#8]
**Дедлайн: 05/03/2024**<br /><br />1. Склонировать текущий репозиторий `<FIRSTNAME>-<LASTNAME>` (например, `ivan-ivanov`) на локальную машину.<br />2. Вывести список всех удаленных репозиториев для локального.<br />3. Вывести список всех веток.<br />4. Вывести последние 3 коммитa с помощью `git log`.<br />5. Создать пустой файл `README.md` и сделать коммит.<br />6. Добавить фразу "Hello, DevOps" в `README.md` файл и сделать коммит.<br />7. Сделать реверт последнего коммита. Вывести последние 3 коммитa с помощью `git log`.<br />8. Удалить последние 3 коммита с помощью `git reset`.<br />9. Вернуть коммит, где добавляется пустой файл `README.md`. Для этого найти ID коммита в `git reflog`, а затем сделать cherry-pick.<br />10. Удалить последний коммит с помощью `git reset`.<br />11. Переключиться на ветку `main` или `master`. Если ветка называется `master`, то переименовать её в `main`.<br />12. Скопировать файл https://github.com/tms-dos21-onl/_sandbox/blob/main/.github/workflows/validate-shell.yaml, положить его по такому же относительному пути в репозиторий. Создать коммит и запушить его в удаленный репозиторий.<br />13. Создать из ветки `main` ветку `develop`. Переключиться на неё и создать `README.md` в корне репозитория. Написать в этом файле какие инструменты DevOps вам знакомы и с какими вы бы хотели познакомиться больше всего (2-3 пункта). Сделать коммит.<br /><br />> :warning: **Для выполнения задания использовать Markdown, а именно заголовок и списки**<br /><br />14. Создать из ветки `main` ветку `support` и создать там файл `LICENSE` в корне репозитория с содержимым https://www.apache.org/licenses/LICENSE-2.0.txt. Сделать коммит. Вывести последние 3 коммитa.<br />15. Переключиться обратно на ветку `main` и создать там файл `LICENSE` в корне репозитория с содержимым https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt. Сделать коммит. Вывести последние 3 коммитa.<br />16. Сделать merge ветки `support` в ветку `main` и решить конфликты путем выбора содержимого любой одной лицензии.<br />17. Переключиться на ветку `develop` и сделать rebase относительно ветки `main`.<br />18. Вывести историю последних 10 коммитов в виде графа с помощью команды `git log -10 --oneline --graph`.<br />19. Запушить ветку `develop`. В истории коммитов должен быть мерж `support -> main`.<br />20. Зайти в свой репозиторий на GitHub и создать Pull Request из ветки `develop` в ветку `main`.

**Comment by glebvadims** [comment]
HW8 выполнена @AlexPykavy

**Comment by AlexPykavy** [comment]
Засчитано!
